In [4]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']= '2'
import tensorflow as tf

In [15]:
a1=tf.constant(4.0,shape=(1,1), dtype=tf.float32)
a2= tf.constant([[1,2,3],[2,4,5]])
a3= tf.ones((3,3))
a4= tf.zeros((2,3))
a5=tf.eye(4)
a6=tf.random.uniform((2,3),minval=2, maxval=5)
a7= tf.random.normal((3,4),mean=0, stddev=1)
a8=tf.range(start=1, limit=11, delta=2)
a9=tf.cast(a2,dtype=tf.float64)
print(a1)
print("*************************************************************")
print(a2)
print("*************************************************************")
print(a3)
print("*************************************************************")
print(a4)
print("*************************************************************")
print(a5)
print("*************************************************************")
print(a6)
print("*************************************************************")
print(a7)
print("*************************************************************")
print(a8)
print("*************************************************************")
print(a9)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
*************************************************************
tf.Tensor(
[[1 2 3]
 [2 4 5]], shape=(2, 3), dtype=int32)
*************************************************************
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
*************************************************************
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
*************************************************************
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
*************************************************************
tf.Tensor(
[[4.3013945 3.0152788 4.4953537]
 [3.836636  4.6559086 4.9722395]], shape=(2, 3), dtype=float32)
*************************************************************
tf.Tensor(
[[-0.8520847  -0.0179329   0.10579027  0.84036297]
 [-0.90332276  0.55338484 -0.6828129   0.22431162]
 [ 0.19476224 -0.46277896  0.56681156  0.70972306]], sha